# Generated by Django 5.2.12 on 2026-04-19 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_academicyear_academics_single_active_year_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPhase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phase_type', models.CharField(choices=[('ACCOUNT_SETUP', 'Account Setup'), ('SUBJECT_SUBMISSION_AND_REVIEW', 'Subject Submission and Review'), ('FIRST_WISH_SELECTION', 'First Wish Selection'), ('RESULTS_AND_APPEALS', 'Results and Appeals'), ('SECOND_WISH_SELECTION', 'Second Wish Selection'), ('FINAL_RESULTS_AND_ASSIGNMENT', 'Final Results and Assignment'), ('WORK_PERIOD', 'Work Period'), ('DEFENSE_PERIOD', 'Defense Period')], max_length=50)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_phases', to='academics.academicyear')),
            ],
            options={
                'db_table': 'campaigns_campaign_phase',
                'ordering': ['academic_year', 'display_order', 'start_at'],
                'indexes': [models.Index(fields=['academic_year'], name='campaigns_phase_year_idx'), models.Index(fields=['phase_type'], name='campaigns_phase_type_idx'), models.Index(fields=['is_archived'], name='campaigns_phase_archived_idx')],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'phase_type'), name='campaigns_unique_phase_type_per_year'), models.UniqueConstraint(fields=('academic_year', 'display_order'), name='campaigns_unique_phase_order_per_year')],
            },
        ),
    ]
