# Generated by Django 5.2.12 on 2026-04-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaignphase',
            name='campaigns_phase_archived_idx',
        ),
        migrations.RemoveField(
            model_name='campaignphase',
            name='is_archived',
        ),
    ]
