# Generated by Django 5.2.12 on 2026-04-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_end_date_academicyear_start_date'),
        ('campaigns', '0002_remove_campaignphase_campaigns_phase_archived_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignphase',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='campaignphase',
            index=models.Index(fields=['is_archived'], name='campaigns_phase_archived_idx'),
        ),
    ]
