# Generated by Django 5.2.12 on 2026-04-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignphase_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignphase',
            name='phase_type',
            field=models.CharField(choices=[('CAMPAIGN_SETUP', 'Campaign Setup'), ('SUBJECT_MANAGEMENT', 'Subject Management'), ('TEAM_FORMATION', 'Team Formation'), ('WISHLIST_1', 'Wishlist 1'), ('ASSIGNMENT_REVIEW_1', 'Assignment Review 1'), ('RESULTS_AND_APPEALS', 'Results and Appeals'), ('WISHLIST_2', 'Wishlist 2'), ('ASSIGNMENT_REVIEW_2', 'Assignment Review 2'), ('WORK_AND_SUPERVISION', 'Work and Supervision'), ('DEFENSE_WINDOW', 'Defense Window'), ('ARCHIVE', 'Archive')], max_length=50),
        ),
    ]
