# Generated by Django 5.2.12 on 2026-04-24 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_academicyear_end_date_academicyear_start_date'),
        ('teams', '0001_initial'),
        ('topics', '0004_remove_subject_attachment_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('wishlist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selection_round', models.CharField(choices=[('FIRST', 'First'), ('SECOND', 'Second')], default='FIRST', max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('LOCKED', 'Locked'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wishlists', to='academics.academicyear')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_wishlists', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='teams.team')),
            ],
            options={
                'db_table': 'assignments_wishlist',
            },
        ),
        migrations.CreateModel(
            name='WishItem',
            fields=[
                ('wishitem_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wish_items', to='topics.subject')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assignments.wishlist')),
            ],
            options={
                'db_table': 'assignments_wish_item',
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('appeal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appeals', to='academics.academicyear')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='teams.team')),
            ],
            options={
                'db_table': 'assignments_appeal',
                'indexes': [models.Index(fields=['team'], name='assign_appeal_team_idx'), models.Index(fields=['status'], name='assign_appeal_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'SUBMITTED')), fields=('team', 'academic_year'), name='assign_max_one_pending_appeal_per_team_year')],
            },
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['team'], name='assign_wishlist_team_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['academic_year'], name='assign_wishlist_year_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['status'], name='assign_wishlist_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('team', 'selection_round', 'academic_year'), name='assign_unique_team_round_wishlist'),
        ),
        migrations.AddConstraint(
            model_name='wishitem',
            constraint=models.UniqueConstraint(fields=('wishlist', 'rank'), name='assign_unique_wishitem_rank'),
        ),
        migrations.AddConstraint(
            model_name='wishitem',
            constraint=models.UniqueConstraint(fields=('wishlist', 'subject'), name='assign_unique_subject_once_per_wishlist'),
        ),
    ]
