# Generated by Django 5.2.12 on 2026-05-05 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TEAM_INVITATION_RECEIVED', 'Team Invitation Received'), ('TEAM_MEMBER_JOINED', 'Team Member Joined'), ('TEAM_MEMBER_LEFT', 'Team Member Left'), ('TEAM_MEMBER_REMOVED', 'Team Member Removed'), ('LEADERSHIP_TRANSFERRED', 'Leadership Transferred'), ('TEAM_LOCKED', 'Team Locked'), ('SUBJECT_SUBMITTED', 'Subject Submitted'), ('SUBJECT_APPROVED', 'Subject Approved'), ('SUBJECT_REJECTED', 'Subject Rejected'), ('SUBJECT_RESUBMITTED', 'Subject Resubmitted'), ('ASSIGNMENT_RESULT_AVAILABLE', 'Assignment Result Available'), ('APPEAL_SUBMITTED', 'Appeal Submitted'), ('APPEAL_ACCEPTED', 'Appeal Accepted'), ('APPEAL_REJECTED', 'Appeal Rejected'), ('DELIVERABLE_UPLOADED', 'Deliverable Uploaded'), ('DELIVERABLE_REVIEWED', 'Deliverable Reviewed'), ('DELIVERABLE_COMMENT_ADDED', 'Deliverable Comment Added'), ('DEFENSE_REQUESTED', 'Defense Requested'), ('DEFENSE_SUPERVISOR_ACCEPTED', 'Defense Supervisor Accepted'), ('DEFENSE_SUPERVISOR_DENIED', 'Defense Supervisor Denied'), ('DEFENSE_READY_TO_SCHEDULE', 'Defense Ready To Schedule'), ('DEFENSE_SCHEDULED', 'Defense Scheduled'), ('DEFENSE_RESCHEDULED', 'Defense Rescheduled'), ('JURY_ASSIGNED', 'Jury Assigned'), ('PV_UPLOADED', 'PV Uploaded'), ('ACADEMIC_YEAR_CLOSED', 'Academic Year Closed'), ('ACADEMIC_YEAR_FORCE_CLOSED', 'Academic Year Force Closed'), ('ACADEMIC_YEAR_REOPENED', 'Academic Year Reopened'), ('ACADEMIC_YEAR_ARCHIVED', 'Academic Year Archived')], max_length=64)),
                ('importance', models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important')], default='NORMAL', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=16)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'db_table': 'notifications_delivery',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notif_recipient_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='notif_type_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['importance'], name='notif_importance_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notif_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['notification'], name='notif_delivery_notif_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['channel'], name='notif_delivery_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status'], name='notif_delivery_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'channel'), name='notif_unique_delivery_channel'),
        ),
    ]
