# Generated by Django 5.2.12 on 2026-04-24 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_academicyear_end_date_academicyear_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('FORMING', 'Forming'), ('LOCKED', 'Locked'), ('VALIDATED', 'Validated'), ('DISSOLVED', 'Dissolved'), ('ARCHIVED', 'Archived')], default='FORMING', max_length=16)),
                ('selection_round', models.CharField(choices=[('FIRST', 'First'), ('SECOND', 'Second')], default='FIRST', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dissolved_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='academics.academicyear')),
            ],
            options={
                'db_table': 'teams_team',
            },
        ),
        migrations.CreateModel(
            name='TeamParticipant',
            fields=[
                ('participation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('LEADER', 'Leader'), ('MEMBER', 'Member'), ('SUPERVISOR', 'Supervisor')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teams_team_participant',
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['status'], name='teams_team_status_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['academic_year'], name='teams_team_year_idx'),
        ),
        migrations.AddIndex(
            model_name='teamparticipant',
            index=models.Index(fields=['team'], name='teams_part_team_idx'),
        ),
        migrations.AddIndex(
            model_name='teamparticipant',
            index=models.Index(fields=['user'], name='teams_part_user_idx'),
        ),
        migrations.AddIndex(
            model_name='teamparticipant',
            index=models.Index(fields=['role'], name='teams_part_role_idx'),
        ),
        migrations.AddIndex(
            model_name='teamparticipant',
            index=models.Index(fields=['status'], name='teams_part_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'LEADER'), ('status', 'ACTIVE')), fields=('team',), name='teams_one_active_leader_per_team'),
        ),
    ]
