# Generated by Django 5.2.12 on 2026-04-24 21:56

import apps.teams.models
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teamparticipant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='teamparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default=apps.teams.models.generate_team_code, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamparticipant',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='teamparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('team', 'user', 'role'), name='teams_unique_active_user_role_per_team'),
        ),
        migrations.AddConstraint(
            model_name='teamparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'MEMBER'), ('status', 'PENDING')), fields=('team', 'user'), name='teams_unique_pending_member_invite'),
        ),
    ]
