# Generated by Django 5.2.12 on 2026-04-24 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_updated_at_teamparticipant_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teamparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'SUPERVISOR'), ('status', 'ACTIVE')), fields=('team', 'user'), name='teams_unique_active_supervisor'),
        ),
    ]
