# Generated by Django 5.2.12 on 2026-04-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teamparticipant_teams_unique_active_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='annual_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
