# Generated by Django 5.2.12 on 2026-05-05 01:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_academicyear_wishlist_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CLOSED', 'Closed'), ('FORCE_CLOSED', 'Force Closed'), ('REOPENED', 'Reopened'), ('ARCHIVED', 'Archived')], max_length=24)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='academics.academicyear')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_year_lifecycle_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'archives_academic_year_lifecycle_event',
                'ordering': ['-performed_at', '-created_at'],
                'indexes': [models.Index(fields=['academic_year'], name='archive_life_year_idx'), models.Index(fields=['event_type'], name='archive_life_event_idx'), models.Index(fields=['performed_at'], name='archive_life_time_idx')],
            },
        ),
    ]
