# Generated by Django 5.2.12 on 2026-05-05 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('USER_IMPORT_PREVIEWED', 'User Import Previewed'), ('USER_IMPORT_COMPLETED', 'User Import Completed'), ('USER_CREATED_BY_IMPORT', 'User Created By Import'), ('ACADEMIC_YEAR_CLOSED', 'Academic Year Closed'), ('ACADEMIC_YEAR_FORCE_CLOSED', 'Academic Year Force Closed'), ('ACADEMIC_YEAR_REOPENED', 'Academic Year Reopened'), ('ACADEMIC_YEAR_ARCHIVED', 'Academic Year Archived'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_ARCHIVED', 'User Archived'), ('PLATFORM_GRANT_CREATED', 'Platform Grant Created'), ('PLATFORM_GRANT_REVOKED', 'Platform Grant Revoked'), ('TEAM_ADMIN_MODIFIED', 'Team Admin Modified'), ('TEAM_DISSOLVED', 'Team Dissolved'), ('SUBJECT_APPROVED', 'Subject Approved'), ('SUBJECT_REJECTED', 'Subject Rejected'), ('ASSIGNMENT_RUN_BY_ADMIN', 'Assignment Run By Admin'), ('APPEAL_REVIEWED', 'Appeal Reviewed'), ('DEFENSE_SCHEDULED', 'Defense Scheduled'), ('DEFENSE_RESCHEDULED', 'Defense Rescheduled'), ('DEFENSE_JURY_UPDATED', 'Defense Jury Updated'), ('DEFENSE_PV_UPLOADED', 'Defense PV Uploaded')], max_length=64)),
                ('target_model', models.CharField(blank=True, max_length=128)),
                ('target_id', models.CharField(blank=True, max_length=128)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_admin_action_log',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['actor'], name='audit_admin_actor_idx'), models.Index(fields=['action_type'], name='audit_admin_action_idx'), models.Index(fields=['target_model'], name='audit_admin_target_model_idx'), models.Index(fields=['occurred_at'], name='audit_admin_occurred_idx')],
            },
        ),
    ]
