# Generated by Django 5.2.12 on 2026-04-24 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_academicyear_end_date_academicyear_start_date'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableSubmission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('REPORT', 'Report'), ('CAHIER_DES_CHARGES', 'Cahier des charges'), ('OTHER', 'Other')], max_length=24)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('file_url', models.CharField(max_length=500)),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('NEEDS_REVISION', 'Needs revision'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('review_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverable_submissions', to='academics.academicyear')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_deliverables', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_submissions', to='teams.team')),
            ],
            options={
                'db_table': 'deliverables_submission',
                'indexes': [models.Index(fields=['team'], name='deliverables_team_idx'), models.Index(fields=['type'], name='deliverables_type_idx'), models.Index(fields=['review_status'], name='deliverables_review_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'type', 'version_number'), name='deliverables_unique_version_per_team_type')],
            },
        ),
    ]
