# Generated by Django 5.2.12 on 2026-04-28 15:39

import apps.deliverables.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0001_initial'),
        ('teams', '0005_team_assignment_validated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.deliverables.models.deliverable_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('NEEDS_REVISION', 'Needs Revision'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_deliverable_files', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverable_files', to='teams.team')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_deliverable_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deliverables_file',
                'ordering': ['-uploaded_at', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DeliverableSubmission',
        ),
        migrations.AddIndex(
            model_name='deliverablefile',
            index=models.Index(fields=['team'], name='deliverables_file_team_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverablefile',
            index=models.Index(fields=['uploaded_by'], name='deliverables_file_uploader_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverablefile',
            index=models.Index(fields=['review_status'], name='deliverables_file_review_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverablefile',
            index=models.Index(fields=['uploaded_at'], name='deliverables_file_uploaded_idx'),
        ),
    ]
