# Generated by Django 5.2.12 on 2026-04-28 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0002_deliverablefile_delete_deliverablesubmission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableFileComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverable_file_comments', to=settings.AUTH_USER_MODEL)),
                ('deliverable_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='deliverables.deliverablefile')),
            ],
            options={
                'db_table': 'deliverables_file_comment',
                'ordering': ['created_at', 'updated_at'],
                'indexes': [models.Index(fields=['deliverable_file'], name='deliverables_comment_file_idx'), models.Index(fields=['author'], name='deliv_comment_author_idx'), models.Index(fields=['created_at'], name='deliv_comment_created_idx')],
            },
        ),
    ]
