# Generated by Django 5.2.12 on 2026-04-19 17:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_academic_year'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_administrative_staff_profile',
            },
        ),
        migrations.CreateModel(
            name='ExternalSupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_external_supervisor_profile',
            },
        ),
        migrations.CreateModel(
            name='PlatformAccessGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin')], max_length=20)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_platform_access_grant',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='business_identity',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMINISTRATIVE_STAFF', 'Administrative Staff'), ('EXTERNAL_SUPERVISOR', 'External Supervisor')], default='STUDENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['business_identity'], name='accounts_user_identity_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_status'], name='accounts_user_status_idx'),
        ),
        migrations.AddField(
            model_name='administrativestaffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalsupervisorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_supervisor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformaccessgrant',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_platform_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformaccessgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='platformaccessgrant',
            index=models.Index(fields=['user'], name='acc_plat_access_user_idx'),
        ),
        migrations.AddIndex(
            model_name='platformaccessgrant',
            index=models.Index(fields=['access_level'], name='acc_plat_access_lvl_idx'),
        ),
        migrations.AddIndex(
            model_name='platformaccessgrant',
            index=models.Index(fields=['revoked_at'], name='acc_plat_access_rev_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user',), name='accounts_one_active_platform_access_per_user'),
        ),
    ]
