# Generated by Django 5.2.12 on 2026-04-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_identity_status_and_platform_grants'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_user_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_user_archived_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='global_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_archived',
        ),
    ]
