# Generated by Django 5.2.12 on 2026-04-21 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_accounts_user_role_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('otp_code_hash', models.CharField(max_length=128)),
                ('verification_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_password_reset_otp',
                'indexes': [models.Index(fields=['user'], name='acc_pwd_reset_user_idx'), models.Index(fields=['expires_at'], name='acc_pwd_reset_exp_idx'), models.Index(fields=['consumed_at'], name='acc_pwd_reset_used_idx')],
            },
        ),
    ]
