# Generated by Django 5.2.12 on 2026-04-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='moyenne_generale',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='departement',
        ),
        migrations.AddField(
            model_name='externalsupervisorprofile',
            name='expertise_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='annual_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='cv_file_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='speciality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
