# Generated by Django 5.2.12 on 2026-04-26 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_studentprofile_moyenne_generale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='annual_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
