# Generated by Django 5.2.12 on 2026-04-20 12:18

from django.db import migrations, models


def backfill_academic_year_status(apps, schema_editor):
    AcademicYear = apps.get_model("academics", "AcademicYear")
    for year in AcademicYear.objects.all().iterator():
        if year.is_archived:
            year.status = "ARCHIVED"
        elif year.is_active:
            year.status = "ACTIVE"
        else:
            year.status = "CLOSED"
        year.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicyear_academics_single_active_year_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academicyear',
            name='academics_single_active_year_constraint',
        ),
        migrations.RemoveIndex(
            model_name='academicyear',
            name='academics_year_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='academicyear',
            name='academics_year_archived_idx',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='CLOSED', max_length=16),
        ),
        migrations.RunPython(backfill_academic_year_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='academicyear',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='is_archived',
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['status'], name='academics_year_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('status',), name='academics_single_active_year_constraint'),
        ),
    ]
