# Generated by Django 5.2.12 on 2026-04-26 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_end_date_academicyear_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='wishlist_size',
            field=models.PositiveIntegerField(default=5, help_text='Number of subject choices required in each team wishlist.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
