# Generated by Django 5.2.12 on 2026-04-24 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_academicyear_end_date_academicyear_start_date'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('defense_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('ARCHIVED', 'Archived')], default='REQUESTED', max_length=16)),
                ('pv_file_url', models.CharField(blank=True, max_length=500)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defenses', to='academics.academicyear')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='defense', to='teams.team')),
            ],
            options={
                'db_table': 'defenses_defense',
            },
        ),
        migrations.CreateModel(
            name='DefenseJuryAssignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jury_role', models.CharField(choices=[('PRESIDENT', 'President'), ('EXAMINER', 'Examiner'), ('GUEST', 'Guest')], max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to='defenses.defense')),
                ('juror', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defense_jury_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'defenses_jury_assignment',
            },
        ),
        migrations.AddIndex(
            model_name='defense',
            index=models.Index(fields=['academic_year'], name='defense_year_idx'),
        ),
        migrations.AddIndex(
            model_name='defense',
            index=models.Index(fields=['status'], name='defense_status_idx'),
        ),
        migrations.AddIndex(
            model_name='defensejuryassignment',
            index=models.Index(fields=['defense'], name='jury_defense_idx'),
        ),
        migrations.AddIndex(
            model_name='defensejuryassignment',
            index=models.Index(fields=['jury_role'], name='jury_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='defensejuryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('jury_role', 'PRESIDENT')), fields=('defense',), name='defense_single_president'),
        ),
    ]
