# Generated by Django 5.2.12 on 2026-04-29 13:32

import apps.defenses.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliverables", "0003_deliverablefilecomment"),
        ("teams", "0005_team_assignment_validated_at_and_more"),
        ("defenses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="DefenseJuryAssignment",
        ),
        migrations.DeleteModel(
            name="Defense",
        ),
        migrations.CreateModel(
            name="Defense",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("READY_TO_SCHEDULE", "Ready To Schedule"),
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="REQUESTED",
                        max_length=24,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("final_grade", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("deliberation", models.TextField(blank=True)),
                ("pv_file", models.FileField(blank=True, null=True, upload_to=apps.defenses.models.defense_pv_upload_to)),
                ("pv_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pv_uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pv_uploaded_defenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_defenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduled_defenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defenses",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "defenses_defense",
                "ordering": ["-requested_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DefenseAttachedFile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="added_defense_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "defense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attached_files",
                        to="defenses.defense",
                    ),
                ),
                (
                    "deliverable_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defense_links",
                        to="deliverables.deliverablefile",
                    ),
                ),
            ],
            options={
                "db_table": "defenses_attached_file",
                "ordering": ["order", "added_at"],
            },
        ),
        migrations.CreateModel(
            name="DefenseSupervisorDecision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "decision",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted"), ("DENIED", "Denied")],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "defense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supervisor_decisions",
                        to="defenses.defense",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defense_supervisor_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "defenses_supervisor_decision",
            },
        ),
        migrations.CreateModel(
            name="DefenseJuryAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("PRESIDENT", "President"), ("EXAMINER", "Examiner"), ("GUEST", "Guest")], max_length=16)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_defense_jury_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "defense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jury_assignments",
                        to="defenses.defense",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defense_jury_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "defenses_jury_assignment",
            },
        ),
        migrations.AddIndex(
            model_name="defense",
            index=models.Index(fields=["team"], name="def_team_idx"),
        ),
        migrations.AddIndex(
            model_name="defense",
            index=models.Index(fields=["status"], name="def_status_idx"),
        ),
        migrations.AddIndex(
            model_name="defense",
            index=models.Index(fields=["scheduled_at"], name="def_sched_idx"),
        ),
        migrations.AddConstraint(
            model_name="defenseattachedfile",
            constraint=models.UniqueConstraint(fields=("defense", "deliverable_file"), name="def_unique_attached_file"),
        ),
        migrations.AddConstraint(
            model_name="defenseattachedfile",
            constraint=models.UniqueConstraint(fields=("defense", "order"), name="def_unique_attached_order"),
        ),
        migrations.AddIndex(
            model_name="defenseattachedfile",
            index=models.Index(fields=["defense"], name="def_att_def_idx"),
        ),
        migrations.AddIndex(
            model_name="defenseattachedfile",
            index=models.Index(fields=["deliverable_file"], name="def_att_file_idx"),
        ),
        migrations.AddConstraint(
            model_name="defensesupervisordecision",
            constraint=models.UniqueConstraint(fields=("defense", "supervisor"), name="def_unique_supervisor_decision"),
        ),
        migrations.AddIndex(
            model_name="defensesupervisordecision",
            index=models.Index(fields=["defense"], name="def_sup_dec_def_idx"),
        ),
        migrations.AddIndex(
            model_name="defensesupervisordecision",
            index=models.Index(fields=["supervisor"], name="def_sup_dec_user_idx"),
        ),
        migrations.AddIndex(
            model_name="defensesupervisordecision",
            index=models.Index(fields=["decision"], name="def_sup_dec_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="defensejuryassignment",
            constraint=models.UniqueConstraint(fields=("defense", "user"), name="def_unique_jury_user"),
        ),
        migrations.AddIndex(
            model_name="defensejuryassignment",
            index=models.Index(fields=["defense"], name="def_jury_def_idx"),
        ),
        migrations.AddIndex(
            model_name="defensejuryassignment",
            index=models.Index(fields=["user"], name="def_jury_user_idx"),
        ),
        migrations.AddIndex(
            model_name="defensejuryassignment",
            index=models.Index(fields=["role"], name="def_jury_role_idx"),
        ),
    ]
