# Generated by Django 5.2.12 on 2026-04-14 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('subject_type', models.CharField(choices=[('RESEARCH_PROJECT', 'Research Project'), ('APPLIED_PROJECT', 'Applied Project'), ('STARTUP_PROJECT', 'Startup Project')], max_length=32)),
                ('technologies', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.academicyear')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_subjects', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'topics_subject',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='topics_subject_status_idx'), models.Index(fields=['is_archived'], name='topics_subject_archived_idx'), models.Index(fields=['academic_year'], name='topics_subject_year_idx'), models.Index(fields=['proposed_by'], name='topics_subject_teacher_idx')],
            },
        ),
    ]
