# Generated by Django 5.2.12 on 2026-04-20 12:18

from django.db import migrations


def backfill_subject_archived_status(apps, schema_editor):
    Subject = apps.get_model("topics", "Subject")
    Subject.objects.filter(is_archived=True).exclude(status="ARCHIVED").update(status="ARCHIVED")


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_subject_attachment_key_subject_attachment_mime_type_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_subject_archived_status, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='subject',
            name='topics_subject_archived_idx',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_archived',
        ),
    ]
