# Generated by Django 5.2.12 on 2026-04-24 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_end_date_academicyear_start_date'),
        ('teams', '0001_initial'),
        ('topics', '0003_remove_subject_topics_subject_archived_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='attachment_key',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='attachment_mime_type',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='attachment_original_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='attachment_size_bytes',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='technologies',
        ),
        migrations.AddField(
            model_name='subject',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='assigned_to_team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_subject', to='teams.team'),
        ),
        migrations.AddField(
            model_name='subject',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_code'], name='topics_subject_code_idx'),
        ),
    ]
