# Generated by Django 5.2.12 on 2026-04-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_remove_subject_attachment_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='attachment_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
