# Generated by Django 5.2.12 on 2026-05-05 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImportBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('import_type', models.CharField(choices=[('STUDENTS', 'Students'), ('TEACHERS', 'Teachers')], max_length=16)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Previewed'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PREVIEWED', max_length=16)),
                ('original_filename', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('normalized_rows', models.JSONField(blank=True, default=list)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imports_user_import_batch',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['import_type'], name='imports_batch_type_idx'), models.Index(fields=['status'], name='imports_batch_status_idx'), models.Index(fields=['uploaded_by'], name='imports_batch_uploader_idx')],
            },
        ),
    ]
